print('==='*45)
print('Analisando váriaveis')
print('==='*45)
a = input('Digite algo:')
print('O tipo primitivo desse valor é:{}'.format(type(a)))
print('É um  número? {}'.format(a.isnumeric()))
print('É um número decimal? {}'.format(a.isdecimal()))
print('É uma alfabeto? {}'.format(a.isalpha()))
print('É um alphanúmerico? {}'.format(a.isalnum()))
print('Está em totalmente minusculo? {}'.format(a.islower()))
print('Está em totalmente maiusculo? {}'.format( a.isupper()))
print('Só tem espaço? {}'.format(a.isspace()))
#print('Está capitalizada? {}'.format(a.is))